### ISSUE TITLE
Infotografia-Realidad Aumentada

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/infografia-ElvisS10#1]
![RV-RA_Elvis](https://user-images.githubusercontent.com/72048969/110155473-47a7f000-7dab-11eb-88ab-d2c5f7106b45.png)

**Comment by AxayacatlS** [comment]
Calificación: 17

**Comment by josealfredo79** [comment]
Esta bien y revisado la infografía.
